# Add your additional Hyprland configurations here

# Autostart Waybar
exec-once = ~/.config/waybar/launch.sh

# Rofi launcher
bind = SUPER, D, exec, rofi -show drun

# Waybar blur - for Flot Minimalist macOS-style theme
layerrule = blur on, xray off, ignore_alpha 0.5, match:namespace waybar

# Rofi blur
layerrule = blur on, xray off, ignore_alpha 0.5, animation slide left, match:namespace rofi

# Swaync blur
layerrule = blur on, xray off, ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = blur on, xray off, ignore_alpha 0.5, match:namespace swaync-notification-window

# Nautilus (Files) blur
windowrule = opacity 0.85 0.85, match:class ^(org.gnome.Nautilus)$
